name = \"patriciataques-tarot-astro\"
main = \"dist/server/entry.mjs\"
compatibility_date = \"2026-04-22\"

[[routes]]
pattern = \"patriciataques.com\"
zone_name = \"patriciataques.com\"

[[routes]]
pattern = \"www.patriciataques.com\"
zone_name = \"patriciataques.com\"

assets = { directory = \"dist/client\" }

[observability]
enabled = true

[[kv_namespaces]]
binding = \"SESSION\"
id = \"\"